// 뉴스 기사 스키마들
export const newsArticleSchemas = [
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article1",
        headline: "클릭메이트, 롯데홈쇼핑과 라이브커머스 방송협력으로 성장모델 확대",
        description: "㈜퀸라이브(대표이사 윤정탁) ‘클릭메이트’는 롯데홈쇼핑과 협력을 통해 클릭메이트 특별방송을 추진했다. 롯데홈쇼핑이 보유한 대표 브랜드인 LBL를 비롯해 국내 백화점 브랜드 30여종을 ‘클릭메이트’의 빅셀러와의 매칭을 통해 방송을 추진했다.",
        datePublished: "2025-09-02",
        dateModified: "2025-09-02",
        author: {
            "@type": "Organization",
            name: "매일경제",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://www.mk.co.kr/news/business/11408875",
        image: "https://queenlive.kr/images/audreygyum-news.jpg",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article2",
        headline: "클릭메이트, 패션셀러 제이플러스 방송 한 번에 1억2천만원 매출 달성",
        description: "퀸라이브의 ‘클릭메이트’가 브랜드사와 셀러간 매칭 프로그램을 통해 의미 있는 성과를 창출했다. 지난8월27일, 패션기업 동광코퍼레이션과 클릭메이트의 빅셀러 제이플러스가 함께 진행한 라이브 방송에서 단 4시간 만에 1억2천만원의 매출을 달성한 것이다.",
        datePublished: "2025-09-02",
        dateModified: "2025-09-02",
        author: {
            "@type": "Organization",
            name: "패션비즈",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://fashionbiz.co.kr/article/219169",
        image: "https://queenlive.kr/images/jplus-news.png",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article3",
        headline: "라이브커머스 ‘돌풍’ 클릭메이트, 월 거래액 160억 돌파",
        description: "단골 고객 커머스 플랫폼인 클릭메이트가 지난달 월 기준 거래액 160억원을 돌파하며 커머스 시장에 돌풍을 이끌고 있다.",
        datePublished: "2025-08-18",
        dateModified: "2025-08-18",
        author: {
            "@type": "Organization",
            name: "이뉴스투데이",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://www.enewstoday.co.kr/news/articleView.html?idxno=2316881",
        image: "https://queenlive.kr/images/enewstoday-sens.jpg",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article4",
        headline: "패션그룹 동광인터내셔날, 클릭메이트와 전략적 사업모델 통한 동반성장 추진",
        description: "㈜동광인터내셔날은 ㈜퀸라이브의 클릭메이트 채널을 통한 새로운 성장모델구축 및 동반성장에 양 사가 합의했다고 밝혔다.",
        datePublished: "2025-07-18",
        dateModified: "2025-07-18",
        author: {
            "@type": "Organization",
            name: "동아일보",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://www.donga.com/news/article/all/20250718/132025418/1",
        image: "https://queenlive.kr/images/withdongguang.jpg",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article5",
        headline: "퀸라이브, 브랜드·셀러 협업 ‘Growth with Clickmate’ 포럼",
        description: "단골고객을 기반으로 한 폐쇄형 라이브커머스로 시장에서 폭발적 성장을 이끌고 있는 ㈜퀸라이브(대표 윤정탁)가 제2회 포럼 ‘Growth with Clickmate’를 통해 브랜드와 셀러의 협업모델을 성공적으로 이끌었다고 밝혔다.",
        datePublished: "2025-07-11",
        dateModified: "2025-07-11",
        author: {
            "@type": "Organization",
            name: "중앙일보",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://www.joongang.co.kr/article/25350849",
        image: "https://queenlive.kr/images/conferencegrowth.jpg",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article6",
        headline: "클릭메이트, 대표 셀러 '쓰리백' 단골 10만명 돌파… 단일 방송 매출 4억원 기록",
        description: "라이브커머스 플랫폼 클릭메이트의 입점 셀러 '쓰리백'이 브랜드 론칭 1주년을 맞아 누적 단골 10만명 돌파, 단일 회차 매출 4억원, 주문 7만5천건을 기록했다고 밝혔다.",
        datePublished: "2025-07-08",
        dateModified: "2025-07-08",
        author: {
            "@type": "Organization",
            name: "머니투데이",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://n.news.naver.com/article/008/0005218767?sid=101",
        image: "https://queenlive.kr/images/threebagnewnews.png",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article7",
        headline: "엔라인 '난닝구', 퀸라이브 '클릭메이트'와 시너지 위한 협약 체결",
        description: "엔라인(대표 이정민)의 '난닝구'와 퀸라이브(대표 윤정탁)의 클릭메이트가 동반성장을 위한 협력에 양사의 시너지를 내기로 협약했다.",
        datePublished: "2025-06-05",
        dateModified: "2025-06-05",
        author: {
            "@type": "Organization",
            name: "TENANT news",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "http://tnnews.co.kr/archives/236787",
        image: "https://queenlive.kr/images/news_25_06_05.jpg",
        articleSection: "Technology",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article8",
        headline: "퀸라이브 라이브커머스 대표 셀러 '쓰리백', 4월 방송 실시간 매출 30억 돌파",
        description: "퀸라이브의 대표 셀러 '쓰리백'이 4월 한 달간 진행한 라이브 방송에서 실시간 매출 30억원을 돌파했습니다.",
        datePublished: "2025-05-02",
        dateModified: "2025-05-02",
        author: {
            "@type": "Organization",
            name: "머니투데이",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://news.mt.co.kr/mtview.php?no=2025050214390438436",
        image: "https://queenlive.kr/images/news_25_05_02.png",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article9",
        headline: '퀸라이브, 2월 거래액 90억 원 돌파…"셀러 성장 지원 효과 입증"',
        description: "퀸라이브가 2월 한 달간 90억 원의 거래액을 달성했습니다. 이는 셀러 중심의 플랫폼 전략과 성장 지원 프로그램의 효과를 입증하는 결과입니다.",
        datePublished: "2025-02-28",
        dateModified: "2025-02-28",
        author: {
            "@type": "Organization",
            name: "머니투데이",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://news.nate.com/view/20250228n25983",
        image: "https://queenlive.kr/images/news_25_02_28.png",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
    {
        "@type": "NewsArticle",
        "@id": "https://queenlive.kr/news#article10",
        headline: "퀸라이브, '2024 컨퍼런스' 성황리 개최...",
        description: "퀸라이브가 '2024 컨퍼런스'를 성황리에 개최했습니다. 컨퍼런스 중 진행된 라이브 방송에서는 단 1시간 만에 5천만원의 매출을 기록했습니다.",
        datePublished: "2024-12-23",
        dateModified: "2024-12-23",
        author: {
            "@type": "Organization",
            name: "시사매거진",
        },
        publisher: {
            "@id": "https://queenlive.kr/#organization",
        },
        url: "https://www.sisamagazine.co.kr/news/articleView.html?idxno=509849",
        image: "https://queenlive.kr/images/news_24_12_23.png",
        articleSection: "Business",
        inLanguage: "ko-KR",
    },
];
